### ISSUE TITLE
不支持批量读写和cas

### ISSUE THREAD

**Issue by flyhope** [easy-swoole/memcache#3]
以下几个命令不支持
* getMulti
* setMulti
* cas

相关文档：
* https://www.php.net/manual/zh/memcached.getmulti.php
* https://www.php.net/manual/zh/memcached.setmulti.php
* https://www.php.net/manual/zh/memcached.cas.php

**Comment by kiss291323003** [comment]
好的。这几天我安排跟进

**Comment by kiss291323003** [comment]
1.1.0已经支持
